Add Turkish Translation
CoralineAda/postmeritocracy pull request #14
Opened 2018-05-29 12:13 UTC by ugurcan377

I translated the manifesto in Turkish.
Will refer this PR to a friend for proofreading.

2018-06-30 20:42 UTC, ugurcan377 commented
Oops, I've forgotten about this pull request, I would be glad if someone can proofread this to a Turkish speaker.

2019-07-03 17:12 UTC, vertexclique requested changes
Reviewed. Needs a leaner, and grammatically fixed rewrite again.

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +* Teknik olmayan katkıların da teknik katkılar kadar faydalı olabileceğinin farkındayız.
Mühendis olmayan insanlar tarafından verilen katkıların olanlar kadar faydalı olabileceğinin farkındayız.

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +* Bu alanda çalışmanın bir hak değil ayrıcalık olduğunu düşünüyoruz. İnsanların teknik becerileri ne kadar iyi olursa olsun, hal ve tavırlarıyla topluluklara zarar verme hakkı olmadığına inanıyoruz.
Son cumle yerine

Çalışma ortamındaki veya daha büyük bir topluluk içindeki zarar verici yapıdaki insanların teknik becerilerinin bu zararlarına zemin oluşturamayacağına inanıyoruz.

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +* Kibir ve rekabete değil şevkat ve dayanışmaya inanıyoruz. Başka insanları programlama dili, aracı ve tekniği kullanımlarından dolayı aşağılamayı reddediyoruz.
Küçümsenmeyi reddediyoruz.

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +* Kibir ve rekabete değil şevkat ve dayanışmaya inanıyoruz. Başka insanları programlama dili, aracı ve tekniği kullanımlarından dolayı aşağılamayı reddediyoruz.
Ilk cümle: Aşağılamaya değil merhametli olmaya inanıyoruz.

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +* Yazılımın teknik gelişim kadar sosyal ve kültürel gelişimi takip etmesi gerektiğine inanıyoruz.
Sadece "sosyal gelişimi"

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +* Lafta kalan ilkelerin bir değerinin olmadığının bilinciyle bu ilkeleri yaptığımız her işe yansıtmayı amaçlıyoruz.
Sözde kalan

2019-07-03 17:12 UTC, vertexclique commented on content/_index.tr.md
> +  İmzacılar listesine eklenmek istiyorsanız, <a href="https://goo.gl/forms/9JT45K1iuKcBSPFj2">bu formu</a> kullanabilirsiniz.
Ïmzalayanlar listesine (klavyemde büyük i yok)

2020-06-18 14:14 UTC, closed without merging